version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Shivamraj@2004
      MYSQL_DATABASE: attendance
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: fastapi_pass
    ports:
      - "3307:3306"   # Changed host port to 3307 to avoid conflict
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ../server/app
      dockerfile: ../../docker/Dockerfile.backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: fastapi_pass
      MYSQL_HOST: db
      MYSQL_DATABASE: attendance
    depends_on:
      - db

  frontend:
    build:
      context: ../client
      dockerfile: ../docker/Dockerfile.frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  mysql_data:
